# Generated by Django 3.0.6 on 2020-05-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('Action_Name', models.TextField(primary_key=True, serialize=False)),
                ('icon', models.TextField()),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_cord', models.FloatField()),
                ('Y_cord', models.FloatField()),
                ('Range', models.FloatField()),
                ('Info_title', models.CharField(max_length=64)),
                ('Info_snipet', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.Action')),
                ('Marker_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.Marker')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_y', models.FloatField()),
                ('position_x', models.FloatField()),
                ('_range', models.FloatField()),
                ('action_position', models.IntegerField()),
                ('title', models.TextField()),
                ('icon', models.TextField()),
                ('description', models.TextField()),
                ('action_detail', models.TextField()),
                ('Action_Name', models.ManyToManyField(to='backup.Action')),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
