# Generated by Django 3.0.6 on 2021-02-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action_Name', models.TextField()),
                ('icon', models.TextField()),
                ('action_position', models.IntegerField()),
                ('action_detail', models.TextField()),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Queue', models.IntegerField()),
                ('position_y', models.FloatField()),
                ('position_x', models.FloatField()),
                ('_range', models.FloatField()),
                ('title', models.TextField()),
                ('icon', models.TextField()),
                ('description', models.TextField()),
                ('Action_Name', models.ManyToManyField(to='backup.Action')),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
