# Generated by Django 3.0.4 on 2020-03-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.Action')),
                ('Marker_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.Marker')),
            ],
        ),
    ]
