# Generated by Django 3.0.6 on 2021-02-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointer',
            old_name='Queue',
            new_name='queue',
        ),
    ]
